version: "3.8"
services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    #restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    user: "${USER_ID}"
    volumes:
      - ./Grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}    
    depends_on:
      - influxdb
      
  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    container_name: influxdb
    #restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    user: "${USER_ID}"
    volumes:
      - ./Influxdb:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
      
  telegraf:
    image: telegraf:${TELEGRAPH_VERSION}
    container_name: telegraf
    env_file:
      - ./.env
    #restart: always
    links:
      - influxdb
    networks:
      - monitoring
    volumes:
     - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
networks:
  monitoring: